# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tbsm delivery emailer

on:
  schedule:
    - cron: '10 12 * * 1-6'
  workflow_dispatch:
jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade 
          pip install pandas nsepython requests pdfkit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update package list
        run: sudo apt-get update -y

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf
    
      - name: Run Python script
        env: 
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python dataupdater_v2.py
